[Renew] custom rules support sonar 9.9
SonarOpenCommunity/cxx-custom-checks-example-plugin pull request #23
Opened 2024-02-28 12:05 UTC by smileQiny

2024-02-28 12:13 UTC, smileQiny commented
test demo：![image](https://github.com/SonarOpenCommunity/cxx-custom-checks-example-plugin/assets/137695008/d9a90f8f-670a-4a61-ab8c-f7561174c6e5)
![image](https://github.com/SonarOpenCommunity/cxx-custom-checks-example-plugin/assets/137695008/79bb98fd-9473-4ed6-9317-d4fa38544f2d)

2024-03-04 16:24 UTC, guwirth requested changes
HI @smileQiny,

looking to the code and past issues:
* https://github.com/SonarOpenCommunity/sonar-cxx/pull/667
* https://github.com/SonarOpenCommunity/sonar-cxx/issues/1308

A solution must use:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/d9a044196e2679301a180761dbae3a424ebc2e95/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/CustomCxxRulesDefinition.java#L33

The CxxSquidSensor is using CustomCxxRulesDefinition:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/d9a044196e2679301a180761dbae3a424ebc2e95/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/CxxSquidSensor.java#L116 

Finally addCustomChecks is called:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/d9a044196e2679301a180761dbae3a424ebc2e95/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/CxxChecks.java#L57

Maybe I understand it wrong? But current solution seems to be different?

Regards,

2024-03-04 16:24 UTC, guwirth commented on pom.xml
> +      <version>2.1.1-SNAPSHOT</version>
Think this must be the version of the plugin. The "-SNAPSHOT" is replaced with the build number.

2024-03-04 16:24 UTC, guwirth commented on pom.xml
> +          <source>10</source>
This is 

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven-compiler.version}</version>
          <configuration>
            <encoding>UTF-8</encoding>
            <showDeprecation>true</showDeprecation>
            <release>${java.version}</release>
            <debug>true</debug>
          </configuration>
        </plugin>

with 
<java.version>11</java.version>
<maven-compiler.version>3.12.1</maven-compiler.version>

see https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/pom.xml

2024-03-04 16:24 UTC, guwirth commented on pom.xml
>        <artifactId>sonar-plugin-api</artifactId>
Would keep this:

      <dependency>
        <groupId>org.sonarsource.api.plugin</groupId>
        <artifactId>sonar-plugin-api</artifactId>
        <version>${sonar.plugin.api.version}</version>
      </dependency>
      <dependency>
        <groupId>org.sonarsource.sonarqube</groupId>
        <artifactId>sonar-plugin-api-impl</artifactId>
        <version>${sonar.version}</version>
      </dependency>
      <dependency>
        <groupId>org.sonarsource.sonarqube</groupId>
        <artifactId>sonar-testing-harness</artifactId>
        <version>${sonar.version}</version>
      </dependency>

with
    <sonar.version>9.9.0.65466</sonar.version>
    <sonar.plugin.api.version>9.14.0.375</sonar.plugin.api.version>

2024-03-05 19:50 UTC, guwirth commented
@smileQiny please have a look to #24

2024-03-06 07:18 UTC, guwirth commented
I merge this one and later one #24

2024-03-06 07:18 UTC, merged